### ISSUE TITLE
Gas price limiter causing reversions for all USDB transactions for older Katana USDB Hub and Peg USDB vault TX with USDB!

### ISSUE THREAD

**Issue by cleancoindev** [bancorprotocol/bancor-contracts-solidity-legacy#4]
This limiter appears to be causing problems.

I want to upgrade my old legacy pool to v2.1 but i cannot do any transactions without a reversion.

I have been discussing this with Glenn in length on discord and you a little but I think I may have pinned down the issue.

If this needs to be updated for the USDB system from the Top level yudi, you'd have to be the guy to upgrade the prices to accounting for the high GWEI costs these days in gas.

Fortunately you built in a way to fix it:
    /**
      * @dev allows the owner to update the gas price limit
      * 
      * @param _gasPrice    new gas price limit
    */
    function setGasPrice(uint256 _gasPrice)
        public
        ownerOnly
        greaterThanZero(_gasPrice)
    {
        gasPrice = _gasPrice;
    }
    
    I do not think this is a Per-converter thing, but a protocol systemic limit.  Thus only the private key owner for the system [I believe this is you Yudi] can change this limiter.
    
Please upgrade this so i can finish my converter upgrade?  I am stuck halfway through with it!
    
    Thanks!

**Comment by cleancoindev** [comment]
@yudilevi

**Comment by yudilevi** [comment]
which pool i it? can you share its address?

**Comment by cleancoindev** [comment]
https://etherscan.io/token/0x94A2aAA374A8F2D52dad24330C8a0Ec2934700ae?a=0x7754717cda23eff9e0962a10e9bb5b95ad2f4cdb  

- here is one.  there's some others but all of them are USDB and they all seem to have the issue.  I noticed there's a repo with bancor smart contracts that appear to have programmed in a workaround for these issues sometime after the repo was released, a year or so later+?

Here is the workaround they seem to have made, whoever they are a long while back with some kind of "addExtraGasLimit" that was not in the original legacy bancor solidity repo i don't think....

https://github.com/ripio/converter-bancor/blob/abd20918b0abbdcdcf6b2262b4925412c60b8938/contracts/TokenConverterRouter.sol#L166

**Comment by yudilevi** [comment]
since we have a discussion on discord, I'm closing this one.
